---
# Phusion yum repo does not have passenger packages available as of 17/06/2016
- include: passenger-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: passenger-Debian.yml
  when: ansible_os_family == 'Debian'
