FROM ubuntu:14.04

MAINTAINER Chinedu Uzoka <cuzoka@mgage.com>

ENV ANSIBLE_ROLE_PATH /etc/ansible/roles

RUN apt-get update && apt-get install -y software-properties-common apt-transport-https \
    && apt-add-repository -y ppa:ansible/ansible 

RUN apt-get update && apt-get install -y ansible

RUN echo '[test]\nlocalhost ansible_connection=local ansible_python_interpreter=python\n' >  /etc/ansible/hosts 

RUN rm -fr /var/cache/apt/archives && rm -fr /var/lib/apt/lists/*

