FROM centos:6

MAINTAINER Chinedu Uzoka <cuzoka@mgage.com>

# Do not install package documentation
RUN yum -y install epel-release \
    && yum -y install ansible

RUN echo -e '[test]\nlocalhost ansible_connection=local ansible_python_interpreter=python\n' >  /etc/ansible/hosts 

COPY ./ansible.cfg /etc/ansible/ansible.cfg

ENV ANSIBLE_ROLE_PATH /etc/ansible/roles

RUN yum clean all

